//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEPApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Sessions = new HashSet<Session>();
            this.Members = new HashSet<Member>();
        }
    
        public int id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public string Lecturer { get; set; }
    
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<Member> Members { get; set; }
    }
}
